# Generated by Django 4.1 on 2022-11-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordfee',
            fields=[
                ('rollid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('fees', models.CharField(max_length=100)),
                ('selectclass', models.CharField(default='Master', max_length=500)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Studentfees',
        ),
    ]
